-- ============================================================
-- AI 角色扮演聊天机器人 —— Supabase 完整建表脚本
-- 在 Supabase SQL Editor 中一次性运行本脚本即可完成所有配置
-- ============================================================

-- 1. 删除旧触发器（幂等，可重复运行）
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS handle_new_user();

-- 2. 世界观表（需最先创建，因为 bots/stories 引用它）
CREATE TABLE IF NOT EXISTS worldviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  era TEXT DEFAULT '',
  technology TEXT DEFAULT '',
  world_events TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 角色表
CREATE TABLE IF NOT EXISTS bots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  avatar TEXT DEFAULT '🤖',
  avatar_url TEXT DEFAULT '',
  personality TEXT DEFAULT '',
  backstory TEXT DEFAULT '',
  theme_color TEXT DEFAULT '#6366f1',
  model TEXT DEFAULT 'deepseek-chat',
  worldview_id BIGINT REFERENCES worldviews(id) ON DELETE SET NULL,
  basic_info TEXT DEFAULT '',
  appearance TEXT DEFAULT '',
  background_url TEXT DEFAULT '',
  speaking_style TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 单聊消息表
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  bot_id BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. 用户设置表（存储 LLM / 生图 API 配置）
CREATE TABLE IF NOT EXISTS user_settings (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  api_key TEXT DEFAULT '',
  api_base_url TEXT DEFAULT 'https://api.deepseek.com/v1',
  default_model TEXT DEFAULT 'deepseek-chat',
  display_name TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  gender TEXT DEFAULT '',
  image_api_key TEXT DEFAULT '',
  image_api_base_url TEXT DEFAULT '',
  image_model TEXT DEFAULT '',
  image_size TEXT DEFAULT '1024x1024',
  image_quality TEXT DEFAULT 'standard',
  image_style TEXT DEFAULT '',
  speaking_style TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. 剧本表
CREATE TABLE IF NOT EXISTS stories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  background TEXT DEFAULT '',
  worldview_id BIGINT REFERENCES worldviews(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. 剧本角色关联表
CREATE TABLE IF NOT EXISTS story_characters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  bot_id BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE
);

-- 8. 剧本消息表
CREATE TABLE IF NOT EXISTS story_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  story_id BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. 更新时间戳函数
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS bots_updated_at ON bots;
CREATE TRIGGER bots_updated_at BEFORE UPDATE ON bots
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS settings_updated_at ON user_settings;
CREATE TRIGGER settings_updated_at BEFORE UPDATE ON user_settings
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

-- ============================================================
-- Row Level Security（行级安全）—— 每个用户只能访问自己的数据
-- ============================================================

-- worldviews
ALTER TABLE worldviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "worldviews_select" ON worldviews;
CREATE POLICY "worldviews_select" ON worldviews FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "worldviews_insert" ON worldviews;
CREATE POLICY "worldviews_insert" ON worldviews FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "worldviews_update" ON worldviews;
CREATE POLICY "worldviews_update" ON worldviews FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "worldviews_delete" ON worldviews;
CREATE POLICY "worldviews_delete" ON worldviews FOR DELETE USING (auth.uid() = user_id);

-- bots
ALTER TABLE bots ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bots_select" ON bots;
CREATE POLICY "bots_select" ON bots FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "bots_insert" ON bots;
CREATE POLICY "bots_insert" ON bots FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "bots_update" ON bots;
CREATE POLICY "bots_update" ON bots FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "bots_delete" ON bots;
CREATE POLICY "bots_delete" ON bots FOR DELETE USING (auth.uid() = user_id);

-- messages
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "messages_select" ON messages;
CREATE POLICY "messages_select" ON messages FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "messages_insert" ON messages;
CREATE POLICY "messages_insert" ON messages FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "messages_delete" ON messages;
CREATE POLICY "messages_delete" ON messages FOR DELETE USING (auth.uid() = user_id);

-- user_settings
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "settings_select" ON user_settings;
CREATE POLICY "settings_select" ON user_settings FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "settings_insert" ON user_settings;
CREATE POLICY "settings_insert" ON user_settings FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "settings_update" ON user_settings;
CREATE POLICY "settings_update" ON user_settings FOR UPDATE USING (auth.uid() = user_id);

-- stories
ALTER TABLE stories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "stories_select" ON stories;
CREATE POLICY "stories_select" ON stories FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "stories_insert" ON stories;
CREATE POLICY "stories_insert" ON stories FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "stories_update" ON stories;
CREATE POLICY "stories_update" ON stories FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "stories_delete" ON stories;
CREATE POLICY "stories_delete" ON stories FOR DELETE USING (auth.uid() = user_id);

-- story_characters
ALTER TABLE story_characters ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "story_chars_select" ON story_characters;
CREATE POLICY "story_chars_select" ON story_characters FOR SELECT USING (
  EXISTS (SELECT 1 FROM stories WHERE id = story_id AND user_id = auth.uid())
);
DROP POLICY IF EXISTS "story_chars_insert" ON story_characters;
CREATE POLICY "story_chars_insert" ON story_characters FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM stories WHERE id = story_id AND user_id = auth.uid())
);
DROP POLICY IF EXISTS "story_chars_delete" ON story_characters;
CREATE POLICY "story_chars_delete" ON story_characters FOR DELETE USING (
  EXISTS (SELECT 1 FROM stories WHERE id = story_id AND user_id = auth.uid())
);

-- story_messages
ALTER TABLE story_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "story_msgs_select" ON story_messages;
CREATE POLICY "story_msgs_select" ON story_messages FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "story_msgs_insert" ON story_messages;
CREATE POLICY "story_msgs_insert" ON story_messages FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "story_msgs_delete" ON story_messages;
CREATE POLICY "story_msgs_delete" ON story_messages FOR DELETE USING (auth.uid() = user_id);

-- ============================================================
-- 索引
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_worldviews_uid ON worldviews(user_id);
CREATE INDEX IF NOT EXISTS idx_bots_uid ON bots(user_id);
CREATE INDEX IF NOT EXISTS idx_msgs_uid ON messages(user_id);
CREATE INDEX IF NOT EXISTS idx_msgs_bid ON messages(bot_id);
CREATE INDEX IF NOT EXISTS idx_msgs_ca ON messages(created_at);
CREATE INDEX IF NOT EXISTS idx_stories_uid ON stories(user_id);
CREATE INDEX IF NOT EXISTS idx_story_chars_sid ON story_characters(story_id);
CREATE INDEX IF NOT EXISTS idx_story_msgs_sid ON story_messages(story_id);
CREATE INDEX IF NOT EXISTS idx_story_msgs_uid ON story_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_story_msgs_ca ON story_messages(created_at);
