-- ============================================
-- 修复 Supabase 注册 500 错误
-- 请在 Supabase SQL Editor 中完整运行本脚本
-- 这会删除旧触发器，用更可靠的方式替代
-- ============================================

-- 1. 删除之前的问题触发器
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS handle_new_user();

-- 2. 确保表存在（如果之前创建失败）
CREATE TABLE IF NOT EXISTS bots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  avatar TEXT DEFAULT '🤖',
  personality TEXT DEFAULT '',
  backstory TEXT DEFAULT '',
  theme_color TEXT DEFAULT '#6366f1',
  model TEXT DEFAULT 'deepseek-chat',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  bot_id BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_settings (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  api_key TEXT DEFAULT '',
  api_base_url TEXT DEFAULT 'https://api.deepseek.com',
  default_model TEXT DEFAULT 'deepseek-chat',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 更新时间戳函数
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS bots_updated_at ON bots;
CREATE TRIGGER bots_updated_at BEFORE UPDATE ON bots
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

DROP TRIGGER IF EXISTS settings_updated_at ON user_settings;
CREATE TRIGGER settings_updated_at BEFORE UPDATE ON user_settings
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

-- ============ Row Level Security ============

-- bots
ALTER TABLE bots ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bots_select" ON bots;
CREATE POLICY "bots_select" ON bots FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "bots_insert" ON bots;
CREATE POLICY "bots_insert" ON bots FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "bots_update" ON bots;
CREATE POLICY "bots_update" ON bots FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "bots_delete" ON bots;
CREATE POLICY "bots_delete" ON bots FOR DELETE USING (auth.uid() = user_id);

-- messages
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "messages_select" ON messages;
CREATE POLICY "messages_select" ON messages FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "messages_insert" ON messages;
CREATE POLICY "messages_insert" ON messages FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "messages_delete" ON messages;
CREATE POLICY "messages_delete" ON messages FOR DELETE USING (auth.uid() = user_id);

-- user_settings - 宽松策略避免触发器问题
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "settings_select" ON user_settings;
CREATE POLICY "settings_select" ON user_settings FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "settings_insert" ON user_settings;
CREATE POLICY "settings_insert" ON user_settings FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "settings_update" ON user_settings;
CREATE POLICY "settings_update" ON user_settings FOR UPDATE USING (auth.uid() = user_id);

-- ============ 索引 ============
CREATE INDEX IF NOT EXISTS idx_bots_uid ON bots(user_id);
CREATE INDEX IF NOT EXISTS idx_msgs_uid ON messages(user_id);
CREATE INDEX IF NOT EXISTS idx_msgs_bid ON messages(bot_id);
CREATE INDEX IF NOT EXISTS idx_msgs_ca ON messages(created_at);
