-- 添加 basic_info 和 appearance 字段到 bots 表
ALTER TABLE bots ADD COLUMN IF NOT EXISTS basic_info TEXT DEFAULT '';
ALTER TABLE bots ADD COLUMN IF NOT EXISTS appearance TEXT DEFAULT '';

-- 添加缺失的用户设置字段
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS display_name TEXT DEFAULT '';
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS avatar_url TEXT DEFAULT '';
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS gender TEXT DEFAULT '';

-- ============ 剧本功能 ============

-- 剧本表
CREATE TABLE IF NOT EXISTS stories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  background TEXT DEFAULT '',
  worldview_id BIGINT REFERENCES worldviews(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 剧本角色关联表
CREATE TABLE IF NOT EXISTS story_characters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  story_id BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  bot_id BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE
);

-- 剧本消息表
CREATE TABLE IF NOT EXISTS story_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  story_id BIGINT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: stories
ALTER TABLE stories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "stories_select" ON stories;
CREATE POLICY "stories_select" ON stories FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "stories_insert" ON stories;
CREATE POLICY "stories_insert" ON stories FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "stories_update" ON stories;
CREATE POLICY "stories_update" ON stories FOR UPDATE USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "stories_delete" ON stories;
CREATE POLICY "stories_delete" ON stories FOR DELETE USING (auth.uid() = user_id);

-- RLS: story_characters
ALTER TABLE story_characters ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "story_chars_select" ON story_characters;
CREATE POLICY "story_chars_select" ON story_characters FOR SELECT USING (
  EXISTS (SELECT 1 FROM stories WHERE id=story_id AND user_id=auth.uid())
);
DROP POLICY IF EXISTS "story_chars_insert" ON story_characters;
CREATE POLICY "story_chars_insert" ON story_characters FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM stories WHERE id=story_id AND user_id=auth.uid())
);
DROP POLICY IF EXISTS "story_chars_delete" ON story_characters;
CREATE POLICY "story_chars_delete" ON story_characters FOR DELETE USING (
  EXISTS (SELECT 1 FROM stories WHERE id=story_id AND user_id=auth.uid())
);

-- RLS: story_messages
ALTER TABLE story_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "story_msgs_select" ON story_messages;
CREATE POLICY "story_msgs_select" ON story_messages FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "story_msgs_insert" ON story_messages;
CREATE POLICY "story_msgs_insert" ON story_messages FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "story_msgs_delete" ON story_messages;
CREATE POLICY "story_msgs_delete" ON story_messages FOR DELETE USING (auth.uid() = user_id);

-- 索引
CREATE INDEX IF NOT EXISTS idx_stories_uid ON stories(user_id);
CREATE INDEX IF NOT EXISTS idx_story_chars_sid ON story_characters(story_id);
CREATE INDEX IF NOT EXISTS idx_story_msgs_sid ON story_messages(story_id);
CREATE INDEX IF NOT EXISTS idx_story_msgs_uid ON story_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_story_msgs_ca ON story_messages(created_at);

-- ============ 生图功能 ============

ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS image_api_key TEXT DEFAULT '';
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS image_api_base_url TEXT DEFAULT '';
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS image_model TEXT DEFAULT 'nano-banana-pro';
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS image_size TEXT DEFAULT '1024x1024';

ALTER TABLE bots ADD COLUMN IF NOT EXISTS background_url TEXT DEFAULT '';
